# created by: senthil.sk@lge.com
version: "3"
services:

    neo4j20211103:
        image: neo4j:4.1.1
        hostname: neo4j
        container_name: neo4j20211103
        networks:
            - newui_test_20211103
        restart: always
        ports:
            - "8015:7474"
            - "8016:7687"
        volumes:
            - ./apps/ker_ko/neo4j/data:/data
            - ./apps/ker_ko/neo4j/logs:/logs
            - ./apps/ker_ko/:/ker_ko

        environment:
            NEO4J_AUTH: neo4j/test
            NEO4J_dbms_logs_debug_level: DEBUG
            NEO4J_dbms_security_auth__enabled: "false"
            NEO4J_dbms_tx__log_preallocate: "false"
            NEO4J_dbms_tx__log_rotation_retention__policy: "false"
        extra_hosts:
            host.docker.internal: 172.17.0.1
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1" ]
            interval: 30s
            timeout: 10s
            retries: 10

    docsearch20211103:
        build: ./apps/ker_ko/document_based
        image: docsearchimg
        container_name: docsearch20211103
        networks:
            - newui_test_20211103
        ports:
            - "8017:8007"
        volumes:
            - .:/docbased
        extra_hosts:
            host.docker.internal: 172.17.0.1
        command: python -m apps.ker_ko.document_based.main

    classifier20211103:
        image: adoptopenjdk/openjdk8
        container_name: koclassifier20211103
        networks:
            - newui_test_20211103
        volumes:
            - ./apps/ker_ko/dataset/models/classifier/korean_bert/:/ker_ko
        command: java -jar ./ker_ko/lgai-mecab-1.0.0.jar

    ker20211103:
        build:
            context: ./apps/ker_ko
        container_name: kercontainer20211103
        networks:
            - newui_test_20211103
        volumes:
            - .:/ker_ko
        ports:
            - "8018:8009"
        command: bash runserver.sh
        depends_on:
            - docsearch20211103
            - classifier20211103
            - neo4j20211103
networks:
    newui_test_20211103: {}
